# fly.toml app configuration file generated for karasu-lab-api on 2025-10-05T00:26:37+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'karasu-lab-api'
primary_region = 'nrt'

[build]

[env]
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[services]]
  protocol = ''
  internal_port = 0

  [[services.ports]]
    port = 3000
    handlers = ['http']
    force_https = true

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20
    min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
